### ISSUE TITLE
run.py is not working on my data

### ISSUE THREAD

**Issue by bur1k** [AIHunters/AcurusTrack#1]
I encounter this exception:
```
python run.py --detections forTracker.json --video_path forTracker.mp4 --video_name out.mp4 --exp_name res
Traceback (most recent call last):
  File "run.py", line 107, in <module>
    main(args)
  File "run.py", line 80, in main
    global_start_frame=arguments.start_frame, global_end_frame=arguments.end_frame)
  File "/home/abt4/Projects/AcurusTrack/pipeline.py", line 104, in __init__
    self.full_meta = self.initialise_meta(detections, 'full')  # change detections inside
  File "/home/abt4/Projects/AcurusTrack/pipeline.py", line 210, in initialise_meta
    meta_object.apply(preparation)
  File "/home/abt4/Projects/AcurusTrack/processing/meta_processing.py", line 42, in apply
    meta_prep_object.apply(self)
  File "/home/abt4/Projects/AcurusTrack/processing/meta_processing.py", line 133, in apply
    self.prepare_meta(meta_object)
  File "/home/abt4/Projects/AcurusTrack/processing/meta_processing.py", line 107, in decorator
    meta_obj.data, meta_obj.homography, int(os.environ.get('fixed_coordinate_resize_h')),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
As far as I am concerned the problem is caused by a missing homography dict whereas argument _path_to_homography_dict_ is optional. What should I do if I have static camera and do not want to transform my coordinate system?

**Comment by vishneuskaja** [comment]
You should simply set  fixed_coordinate_system to False in your config.py
Also we added a check to our code which messages you "set **fixed_coordinate_system** for **False**" if homography_dict wasn't served for input.

**Comment by bur1k** [comment]
Thank you for your answer.
