### ISSUE TITLE
IndexError: Too many levels: Index has only 1 level, not 2

### ISSUE THREAD

**Issue by wmklalala** [AIHunters/AcurusTrack#15]
Hello, I would like to ask what the level means in   File "AcurusTrack/processing/dataframe_processing.py", line 84, in get_df_info
    start = start.reset_index(level=1, drop=True)?

`(venv) root@868ecbc68d99:/data/AcurusTrack# python3 run.py --detections '../test1.json' --video_path '../test102301.mp4' --video_name 'test102301' --exp_name 'test102301'
Traceback (most recent call last):
  File "run.py", line 110, in <module>
    main(args)
  File "run.py", line 83, in main
    global_start_frame=arguments.start_frame, global_end_frame=arguments.end_frame)
  File "/data/AcurusTrack/pipeline.py", line 110, in __init__
    self.wind_objects = self.prepare_objs_for_each_window()
  File "/data/AcurusTrack/pipeline.py", line 204, in prepare_objs_for_each_window
    processed_meta = DataframeProcessing(meta_object)
  File "/data/AcurusTrack/processing/dataframe_processing.py", line 37, in __init__
    self.clean_meta()
  File "/data/AcurusTrack/processing/dataframe_processing.py", line 78, in clean_meta
    self.dataframe = dataframe_cleaned  # should call all necessary updates
  File "/data/AcurusTrack/processing/dataframe_processing.py", line 56, in dataframe
    self.main_info = self.get_df_info()
  File "/data/AcurusTrack/processing/dataframe_processing.py", line 84, in get_df_info
    start = start.reset_index(level=1, drop=True)
  File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 4565, in reset_index
    level = [self.index._get_level_number(lev) for lev in level]
  File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 4565, in <listcomp>
    level = [self.index._get_level_number(lev) for lev in level]
  File "/usr/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1420, in _get_level_number
    self._validate_index_level(level)
  File "/usr/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1412, in _validate_index_level
    f"Too many levels: Index has only 1 level, not {level + 1}"
IndexError: Too many levels: Index has only 1 level, not 2
`

**Comment by vishneuskaja** [comment]
Hi! Could you please provide us with an example of your input format? 
It will be easier to answer your issue like that. 
Thanks!

**Comment by vishneuskaja** [comment]
@wmklalala hey, have you been able to solve this issue?
If not, you probably have some issues with the pandas data frame. You can see that many people experience this issue. 
Pandas dataframe is formed inside a project automatically. If you have an issue with that, probably your JSON format isn't right.

Please let me know if it helps you!

**Comment by wmklalala** [comment]
Yes, I've solved the issue.
I am sorry for not replying to you in time because I have been busy recently.Thank you for your concern!
